default:
  # local-only configuration
  sparklyr.cores.local: !expr parallel::detectCores()
  spark.sql.shuffle.partitions.local: !expr parallel::detectCores()

  # default spark packages to load
  sparklyr.defaultPackages:
    - com.databricks:spark-csv_2.11:1.3.0
    - com.amazonaws:aws-java-sdk-pom:1.10.34

  # command line arguments to spark-shell
  # sparklyr.shell.*
  
